### PR TITLE
Add logo files and update README with the presentation files

### PR DESCRIPTION
**Pull request by EduardoLopes**

### CODE REVIEW

**Comment by KevinKelbie** [comment]
Woah! These designs are fantastic!

**Comment by sebmck** [comment]
This is so good! Thank you so much @EduardoLopes!

**Comment by sebmck** [comment]
I'll update the GitHub org photo, Twitter, and main repo README.

**Comment by sebmck** [comment]
@EduardoLopes If you'd like, feel free to send another PR to add a link to your website/Twitter/whatever you want in the README.

**Pull request merged**
